version: "3"

networks:
  app-network:
    driver: ${NETWORKS_DRIVER}

volumes:
  dbdata:
    driver: ${VOLUMES_DRIVER}

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile.php
        restart: unless-stopped
        tty: true
        volumes:
            - ./../:/var/www
            - ./php.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - "${APP_PORT}:80"
        volumes:
            - ./../:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network

    redis:
        image: redis:alpine
        restart: unless-stopped
        ports:
            - "${REDIS_PORT}:6379"
        command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
        volumes:
            - ./redis.conf:/usr/local/etc/redis/redis.conf
            - ./data:/.data_redis
        networks:
            - app-network

    supervisor:
        build:
            context: .
            dockerfile: Dockerfile.supervisor
        restart: unless-stopped
        volumes:
            - ./../:/var/www
            - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
        networks:
            - app-network
